# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['pausa_activa.py'],
    pathex=[],
    binaries=[],
    datas=[('FlowBreak.ico', '.'), ('ejercicios.json', '.')],
    hiddenimports=[
        'winotify',
        'pystray',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'winreg',
        'winsound',
        'logging',
        'wave',
        'customtkinter',
        'darkdetect',
        'pausa_activa',
        'pausa_activa.constants',
        'pausa_activa.config',
        'pausa_activa.notifications',
        'pausa_activa.audio',
        'pausa_activa.water',
        'pausa_activa.installer',
        'pausa_activa.windows',
        'pausa_activa.app',
        'pynput',
        'pynput.keyboard',
        'win32com',
        'win32com.client',
        'win32com.client.util',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='FlowBreak',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['FlowBreak.ico'],
)
